import Head from "next/head";
import {
  Box,
  createTheme,
  ThemeProvider,
  Grid,
  Typography,
} from "@mui/material";
import { AppDivider } from "@/components/AppDivider";
import { AppHead } from "@/components/AppHead";
import { TitleHomePage } from "@/components/TitleHomePage";
import { ProjectCard } from "@/components/ProjectCard";
import { AppTopBar } from "@/components/AppTopBar";

const theme = createTheme();
export default function Home() {
  const services = [
    {
      index: 1,
      title: "USER EXPERIENCE",
      description: (
        <Typography>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime
          mollitia, molestiae quas vel sint commodi repudiandae consequuntur
          voluptatum laborum numquam blanditiis harum quisquam eius sed odit
          fugiat iusto fuga praesentium optio, eaque rerum!{" "}
        </Typography>
      ),
    },
    {
      index: 2,
      title: "USER EXPERIENCE",
      description: (
        <Typography>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime
          mollitia, molestiae quas vel sint commodi repudiandae consequuntur
          voluptatum laborum numquam blanditiis harum quisquam eius sed odit
          fugiat iusto fuga praesentium optio, eaque rerum!{" "}
        </Typography>
      ),
    },
    {
      index: 3,
      title: "USER EXPERIENCE",
      description: (
        <Typography>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime
          mollitia, molestiae quas vel sint commodi repudiandae consequuntur
          voluptatum laborum numquam blanditiis harum quisquam eius sed odit
          fugiat iusto fuga praesentium optio, eaque rerum!{" "}
        </Typography>
      ),
    },
    {
      index: 4,
      title: "USER EXPERIENCE",
      description: (
        <Typography>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime
          mollitia, molestiae quas vel sint commodi repudiandae consequuntur
          voluptatum laborum numquam blanditiis harum quisquam eius sed odit
          fugiat iusto fuga praesentium optio, eaque rerum!{" "}
        </Typography>
      ),
    },
  ];

  return (
    <>
      <ThemeProvider theme={theme}>
        <Head>
          <title>Gettapper website</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppHead title={"Getapper Home Page"} />
        <AppTopBar />
        <Box
          sx={{
            width: "70%",
            minHeight: "100vh",
            padding: "15%",
            backgroundImage: `url(https://www.getapper.com/_next/static/media/logo_bg.34e68c96.svg)`,
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
            backgroundPosition: "center 200px",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <TitleHomePage />

          <AppDivider />

          <Typography
            variant="h4"
            sx={{
              margin: "0 auto",
              textAlign: "center",
            }}
          >
            <strong>SOLUZIONI SU MISURA</strong> PER OGNI PROGETTO
          </Typography>

          <Grid container spacing={3} sx={{ mt: "60px" }}>
            {services.map((service) => (
              <ProjectCard
                key={service.index}
                index={service.index}
                title={service.title}
                description={service.description}
              />
            ))}
          </Grid>

          <AppDivider />
        </Box>
      </ThemeProvider>
    </>
  );
}
